# rag/scripts/generate_master_profile.py
import os
import sys
from dotenv import load_dotenv
from langchain_openai import ChatOpenAI
from langchain_core.messages import HumanMessage
import chromadb
from chromadb.utils import embedding_functions

# Ensure we can import from root modules if needed
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "Sample_Project/rag/caree_data")))

# Load environment variables
load_dotenv()

def generate_master_profile():
    print("🚀 Initializing Enhanced FAANG Master Profile Generator...")
    
    api_key = os.getenv("OPENAI_API_KEY")
    if not api_key:
        print("❌ ERROR: OPENAI_API_KEY missing from environment.")
        return

    # 1. Connect to the Career Database
    chroma_client = chromadb.PersistentClient(path="./chroma_db")
    ef = embedding_functions.OpenAIEmbeddingFunction(
        api_key=api_key,
        model_name="text-embedding-3-small"
    )
    
    try:
        career_collection = chroma_client.get_collection(name="career_knowledge", embedding_function=ef)
    except Exception as e:
        print(f"❌ ERROR: Could not find 'career_knowledge' collection. Did you run the ingestion script? Details: {e}")
        return

    # 2. Expanded & Hyper-Targeted Architectural PM Extraction Categories
    extraction_topics = {
        "Career_Overview_&_Impact": (
            "Extract all mentions of resumes, job titles, years of experience, professional achievements, "
            "and core leadership metrics."
        ),
        "AI_&_ML_Product_Management": (
            "Extract all core concepts regarding AI/ML Product Management, lifecycle management, model evaluation "
            "metrics, model development constraints, and metrics used to evaluate machine learning models."
        ),
        "Agentic_&_Multi_Agent_Systems": (
            "Extract all notes, concepts, and frameworks on Agentic AI, Multi-Agent orchestration pipelines, "
            "graph-based state management, routing architectures, and agentic system design principles."
        ),
        "System_Design_&_MLOps_Scale": (
            "Extract all technical notes regarding system design, MLOps, asynchronous execution queues, "
            "Redis caching layers, horizontal scale infrastructure, data isolation firewalls, and backend stability."
        ),
        "SaaS_Product_Management_&_Roadmaps": (
            "Extract all strategic frameworks on SaaS Product Management, product roadmapping, feature prioritization, "
            "agile methodologies, product lifecycle phases, and managing software-as-a-service configurations."
        ),
        "Product_Management_GTM_Strategy": (
            "Extract all foundational strategies for general Product Management Go-To-Market (GTM), distribution, "
            "user acquisition channels, packaging, customer adoption, and enterprise launch strategies."
        ),
        "Solved_AI_Product_Workbooks_&_Case_Studies": (
            "Extract all data blocks detailing solved AI product workbooks, product management case studies, "
            "analytical mock exercises, problem-solving workshops, and concrete product problem scenarios."
        )
    }

    # Using gpt-4o for high-fidelity cross-document synthesis and deduplication
    llm = ChatOpenAI(model="gpt-4o", temperature=0.1) 
    master_markdown_content = "# 👑 FAANG Master AI PM & Architect Knowledge Profile\n\n*Generated by Agentic Synthesis*\n\n---\n\n"

    # 3. The Map-Reduce Execution Loop
    for category_name, query_intent in extraction_topics.items():
        print(f"🔍 Mapping category: {category_name}...")
        
        # MAP: Query the collection broadly to capture nuanced multi-file records
        results = career_collection.query(query_texts=[query_intent], n_results=12)
        
        if not results or not results['documents'] or not results['documents'][0]:
            print(f"   ⚠️ No data found for {category_name}.")
            continue
            
        raw_chunks = results['documents'][0]
        combined_raw_text = "\n\n--- NEXT DOCUMENT FRAGMENT ---\n\n".join(raw_chunks)
        
        # REDUCE: Resolve overlaps, clean up duplicates, synthesize multi-dimensional perspectives
        print(f"🧠 Reducing and Synthesizing {len(raw_chunks)} fragments...")
        
        synthesis_prompt = (
            f"You are an elite Technical Product Coach creating a Master Interview Profile for a Senior/Principal AI Product Manager.\n"
            f"I am providing you with noisy, fragmented, and sometimes overlapping lecture notes and workbooks on: {category_name.replace('_', ' ')}.\n\n"
            f"YOUR TASK:\n"
            f"1. Synthesize this data into a definitive, highly cohesive executive summary section.\n"
            f"2. ELIMINATE REDUNDANCY: If multiple notes or lectures cover the exact same concept, merge them smoothly. Do not repeat definitions.\n"
            f"3. PRESERVE UNIQUE DIMENSIONS: If different documents capture different angles (e.g., one details the strategic roadmap value, while another details the technical implementation math), merge them into a comprehensive description.\n"
            f"4. Format the output cleanly using professional Markdown (subheaders, explicit bullet points, italicized frameworks, bold key metrics).\n"
            f"5. Rely strictly on the provided fragments. Do not invent outside trivia.\n\n"
            f"RAW FRAGMENTS:\n{combined_raw_text}"
        )
        
        response = llm.invoke([HumanMessage(content=synthesis_prompt)])
        clean_section = response.content
        
        # Append to the final document builder string
        master_markdown_content += f"## {category_name.replace('_', ' ')}\n\n{clean_section}\n\n---\n\n"

    # 4. Write Output securely to the local workspace directory
    output_path = os.path.abspath(os.path.join(os.path.dirname(__file__), "../career_data/master_cheat_sheet.md"))
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(master_markdown_content)
        
    print(f"\n✨ SUCCESS: Fully Synthesized Master Profile generated at: {output_path}")

if __name__ == "__main__":
    generate_master_profile()